# Generated by Django 5.1 on 2024-09-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_produktu', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dostępnosc', models.BooleanField()),
            ],
        ),
    ]
