# Generated by Django 5.1 on 2024-09-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='product-<built-in function id>', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
